### ISSUE TITLE
Private KotlinParseTree name property

### ISSUE THREAD

**Issue by EranBoudjnah** [Kotlin/kotlin-grammar-tools#2]
Why is `name` private in `KotlinParseTree`? It makes it virtually impossible to traverse through the tree in a meaningful way in code. I guess it being an enum would also be better than it being a string.

**Comment by petukhovv** [comment]
It has been changed to public via https://github.com/Kotlin/grammar-tools/pull/3

**Comment by blundell** [comment]
These are still private in version 0.1-43 

<img width="1754" alt="image" src="https://user-images.githubusercontent.com/655860/168597056-4354fae8-1aca-40ed-b127-cc3525adc318.png">

a new release is needed (https://github.com/Kotlin/kotlin-grammar-tools/releases)
