### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zhelenskiy** [Kotlin/kotlin-grammar-tools#4]
I tried to clone the repo and build it. But I got:
![image](https://user-images.githubusercontent.com/55230817/84572949-372b9180-ada6-11ea-817c-e8ea5cac0a08.png)
I assume it to be a missed dependency.

**Comment by wilkomanger** [comment]
There's indeed a dependency missing, making it impossible for others to build this project at the moment.

**Comment by NanoSpicer** [comment]
Hi @PetukhovVictor could you please add the missing dependency or publish a new build with the fixes from #3 ?

Thank you in advance

**Comment by ice-phoenix** [comment]
We [added](https://github.com/Kotlin/grammar-tools/commit/7e82b81209add80817aeeeb622d1651dc9d196af) a better description on how one can currently use the `kotlin-grammar-tools` library in the [README](https://github.com/Kotlin/grammar-tools/blob/master/README.md#using). That should somewhat help =)

**Comment by nuwak** [comment]
```
./gradlew :grammar:publishToMavenLocal

FAILURE: Build failed with an exception.

* Where:

* What went wrong:
Could not resolve all files for configuration ':docs:runtimeClasspath'.
> Could not resolve ru.spbstu:g4-to-ebnf:0.0.0.4.
  Required by:
      project :docs
   > Could not resolve ru.spbstu:g4-to-ebnf:0.0.0.4.
      > Could not get resource 'https://maven.vorpal-research.science/ru/spbstu/g4-to-ebnf/0.0.0.4/g4-to-ebnf-0.0.0.4.pom'.
         > Could not GET 'https://maven.vorpal-research.science/ru/spbstu/g4-to-ebnf/0.0.0.4/g4-to-ebnf-0.0.0.4.pom'.
            > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.4.2/userguide/build_environment.html#gradle_system_properties
               > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

**Comment by ice-phoenix** [comment]
The fix for this error is in the Kotlin specification repo, it should work now once you pull the latest updates. Thanks for bringing this to our attention!
